FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY backend/package.json ./backend/

RUN npm install --workspace backend

COPY backend ./backend


FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/backend ./backend

WORKDIR /app/backend

EXPOSE 5000

CMD ["node", "dist/server.js"]
